name: clinic
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  go_router: ^14.8.1
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^0.5.1
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.8.4

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf

flutter_native_splash:
  android: true
  ios: true
  image: assets/images/bg.png
  color: "#ffffff"
  color_dark: "#ffffff"
  android_12:
    image: assets/images/bg.png
    color: "#ffffff"
    color_dark: "#ffffff"
  android_gravity: fill
  ios_content_mode: scaleToFill
