name: clinic
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.5
  flutter_screenutil: ^5.9.3
  go_router: ^14.8.1
  hive_flutter: ^1.1.0
  hugeicons: ^0.0.11
  image_picker: ^1.1.2
  intl: ^0.20.2
  modal_progress_hud_nsn: ^0.5.1
  permission_handler: ^12.0.0+1
  salomon_bottom_bar: ^3.3.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.8.4

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf

flutter_native_splash:
  android: true
  ios: true
  image: assets/images/bg.png
  color: "#ffffff"
  color_dark: "#ffffff"
  android_12:
    image: assets/images/bg.png
    color: "#ffffff"
    color_dark: "#ffffff"
  android_gravity: fill
  ios_content_mode: scaleToFill
