// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXUx1rZsSxwqIa-TSftoaFAerKIz4T_jM',
    appId: '1:317202641209:web:58beaa2bedb2202a00b8e8',
    messagingSenderId: '317202641209',
    projectId: 'clinic-e3e51',
    authDomain: 'clinic-e3e51.firebaseapp.com',
    storageBucket: 'clinic-e3e51.firebasestorage.app',
    measurementId: 'G-LS028KLHSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_wyWtEqUTrfIJ4k5pqj65L2zS9UaiWPw',
    appId: '1:317202641209:android:c9ce44d0a66094c800b8e8',
    messagingSenderId: '317202641209',
    projectId: 'clinic-e3e51',
    storageBucket: 'clinic-e3e51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkv37j_nBx7L76jgt94_sF-yKyPtJ0MYg',
    appId: '1:317202641209:ios:90f15d9ede09fcb200b8e8',
    messagingSenderId: '317202641209',
    projectId: 'clinic-e3e51',
    storageBucket: 'clinic-e3e51.firebasestorage.app',
    iosBundleId: 'com.example.clinic',
  );
}
